name: CI/CD Pipeline

on:
  push:
    branches:
      - dev   # Run only when pushing to dev branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync code to VM directory
        run: |
          # Make sure folder exists
          mkdir -p /home/clouduser/test_cicd

          # Copy latest code to VM directory
          rsync -av --delete ./ /home/clouduser/test_cicd/

      - name: Generate prod.env
        working-directory: /home/clouduser/test_cicd
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > prod.env
          echo "ACQ_API_KEY=${{ secrets.ACQ_API_KEY }}" >> prod.env

      - name: Deploy with Docker Compose
        working-directory: /home/clouduser/test_cicd
        run: |
          docker-compose -f docker-compose.yml down || true
          docker-compose -f docker-compose.yml up -d --build
